modelInputFormat: DICT
featureSources:
  tracks:
    entityType: projects/934903580331/locations/us-central1/featurestores/v2_sp_mpd_candidate_tracks_ndr_v1/entityTypes/tracks
    entityIdField: tracks
features:
- name: track_uri_can
- name: track_name_can
  fetchFrom:
    sourceName: tracks
    featureId: track_name_can
- name: artist_uri_can
  fetchFrom:
    sourceName: tracks
    featureId: artist_uri_can
- name: artist_name_can
  fetchFrom:
    sourceName: tracks
    featureId: artist_name_can
- name: album_uri_can
  fetchFrom:
    sourceName: tracks
    featureId: album_uri_can
- name: album_name_can
  fetchFrom:
    sourceName: tracks
    featureId: album_name_can
- name: duration_ms_can
  fetchFrom:
    sourceName: tracks
    featureId: duration_ms_can
- name: track_pop_can
  fetchFrom:
    sourceName: tracks
    featureId: track_pop_can
- name: artist_pop_can
  fetchFrom:
    sourceName: tracks
    featureId: artist_pop_can
- name: artist_genres_can
  fetchFrom:
    sourceName: tracks
    featureId: artist_genres_can
- name: artist_followers_can
  fetchFrom:
    sourceName: tracks
    featureId: artist_followers_can
- name: track_danceability_can
  fetchFrom:
    sourceName: tracks
    featureId: track_danceability_can
- name: track_energy_can
  fetchFrom:
    sourceName: tracks
    featureId: track_energy_can
- name: track_key_can
  fetchFrom:
    sourceName: tracks
    featureId: track_key_can
- name: track_loudness_can
  fetchFrom:
    sourceName: tracks
    featureId: track_loudness_can
- name: track_mode_can
  fetchFrom:
    sourceName: tracks
    featureId: track_mode_can
- name: track_speechiness_can
  fetchFrom:
    sourceName: tracks
    featureId: track_speechiness_can
- name: track_acousticness_can
  fetchFrom:
    sourceName: tracks
    featureId: track_acousticness_can
- name: track_instrumentalness_can
  fetchFrom:
    sourceName: tracks
    featureId: track_instrumentalness_can
- name: track_liveness_can
  fetchFrom:
    sourceName: tracks
    featureId: track_liveness_can
- name: track_valence_can
  fetchFrom:
    sourceName: tracks
    featureId: track_valence_can
- name: track_tempo_can
  fetchFrom:
    sourceName: tracks
    featureId: track_tempo_can
- name: track_time_signature_can
  fetchFrom:
    sourceName: tracks
    featureId: track_time_signature_can
