name: Spellcheck Action
on: push
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.27.0
      name: Spellcheck
      with:
        config_path: .github/workflows/.spellcheck.yml # put path to configuration file here 
