matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
    wordlists:
    - .wordlists.txt
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: true
      ignores:
      - code
      - pre
  default_encoding: utf-8
  sources:
  - '*.ipynb'
